import type { Metadata } from "next";
import { Belanosima, Nunito_Sans } from "next/font/google";
import "./globals.css";

const belanosima = Belanosima({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-belanosima",
  display: "swap",
});

const nunitoSans = Nunito_Sans({
  subsets: ["latin"],
  variable: "--font-nunito-sans",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="en" className={`${belanosima.variable} ${nunitoSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
